# ================================== #
#             Alacritty              #
# ================================== #

# ====================== #
#         Window         #
# ====================== #

[window]
opacity = 0.85
decorations = "none"
startup_mode = "Windowed"

[font]
size = 8.5


# ====================== #
#         Colors         #
# ====================== #

# [colors.primary]
# background = "0x1e1e2e"
# foreground = "0xcdd6f4"

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"
